---
title: "BioMe_proteome_EDA_s2"
author: "Meizhen Yao"
date: "`r Sys.Date()`"
output:
  html_document:
    theme: united
    highlight: tango
    df_print: paged
    fig_caption: yes
    fig_height: 7
    fig_width: 10
    number_sections: yes
    toc: yes
    toc_float:
      collapsed: yes
      smooth_scroll: yes
    self_contained: yes
    code_folding: hide
    toc_depth: 6
header-includes: \usepackage{multirow}
---

<style type="text/css">
body{
  /*font-family: Helvetica;*/
  font-size: 12pt;
}
</style>


```{r setup, include=FALSE}
options(digits = 4)
knitr::opts_chunk$set(echo = TRUE,tidy=TRUE,cache=F,warning = FALSE)
# suppress warning messages for final rendering
old.warn <- getOption("warn")
options(qwraps2_markup = "markdown")

```



```{r, include=FALSE}
library(tidyverse)
library(ggpubr)
library(data.table)
library(readr)
library(readxl)
library(ComplexHeatmap)
library(OlinkAnalyze)
library(gtsummary)
library(flextable)
library(ggplotify)
library(pheatmap)
library(plotly)
library(gapminder)
library(manipulateWidget)
library(ggfortify)
library(reactable)
library(mice)
library(naniar)
library(WGCNA)

## import data
BioMe_proteome <- fread("C:/Users/yaom03/OneDrive - The Mount Sinai Hospital/Documents/Projects/BioMe/proteome/input/Q-00771_Loos_NPX_2022-05-03/Q-00771_Loos_NPX_2022-05-03.txt")
assay_list<- read_excel("C:/Users/yaom03/OneDrive - The Mount Sinai Hospital/Documents/Projects/BioMe/proteome/input/assay-list-olink-explore-3072.xlsx", sheet = "data")


## remove controls
BioMe_proteome_nocontrol<- BioMe_proteome %>% 
                           filter(!grepl("CONTROL", SampleID))

## combine data with annotation
str(BioMe_proteome_nocontrol)
str(assay_list)

colnames(assay_list)[1]<- "UniProt"
colnames(assay_list)[2]<- "Protein_name"
colnames(assay_list)[3]<- "Gene_name"
colnames(assay_list)[4]<- "Panel"


BioMe_proteome_protname<- BioMe_proteome_nocontrol %>% 
                          left_join(assay_list, by = c("UniProt", "Panel"))



colSums(is.na(BioMe_proteome_protname))
BioMe_proteome_protname %>% filter(is.na(Protein_name)==TRUE)

#------------------------------------------- transpose to wide format
BioMe_proteome_wide<- BioMe_proteome_protname %>% 
                      select(SampleID, OlinkID, NPX) %>% 
                      pivot_wider(
                        names_from = OlinkID,
                        values_from = NPX
                      )



BioMe_proteome_cardio_wide<- BioMe_proteome_protname %>% 
                             filter(Panel == "Cardiometabolic") %>% 
                             select(SampleID, PlateID, OlinkID, NPX) %>% 
                             pivot_wider(
                               names_from = OlinkID,
                               values_from = NPX
                             )




BioMe_proteome_inflam_wide<- BioMe_proteome_protname %>% 
                             filter(Panel == "Inflammation") %>% 
                             select(SampleID, OlinkID, NPX) %>% 
                             pivot_wider(
                               names_from = OlinkID,
                               values_from = NPX
                             )




BioMe_proteome_inflam2_wide<- BioMe_proteome_protname %>% 
                             filter(Panel == "Inflammation_II") %>% 
                             select(SampleID, OlinkID, NPX) %>% 
                             pivot_wider(
                               names_from = OlinkID,
                               values_from = NPX
                             )




BioMe_proteome_oncology_wide<- BioMe_proteome_protname %>% 
                             filter(Panel == "Oncology") %>% 
                             select(SampleID, OlinkID, NPX) %>% 
                             pivot_wider(
                               names_from = OlinkID,
                               values_from = NPX
                             )



BioMe_proteome_Oncology2_wide<- BioMe_proteome_protname %>% 
                             filter(Panel == "Oncology_II") %>% 
                             select(SampleID, OlinkID, NPX) %>% 
                             pivot_wider(
                               names_from = OlinkID,
                               values_from = NPX
                             )


BioMe_proteome_Neurology_wide<- BioMe_proteome_protname %>% 
                             filter(Panel == "Neurology") %>% 
                             select(SampleID, OlinkID, NPX) %>% 
                             pivot_wider(
                               names_from = OlinkID,
                               values_from = NPX
                             )



BioMe_proteome_Neurology2_wide<- BioMe_proteome_protname %>% 
                             filter(Panel == "Neurology_II") %>% 
                             select(SampleID, OlinkID, NPX) %>% 
                             pivot_wider(
                               names_from = OlinkID,
                               values_from = NPX
                             )


```






# WGCNA
```{r, include=FALSE}
#library(WGCNA)
allowWGCNAThreads()          # allow multi-threading (optional)
#> Allowing multi-threading with up to 4 threads.

# Choose a set of soft-thresholding powers
powers = c(c(1:10), seq(from = 12, to = 20, by = 2))

# Call the network topology analysis function
sft = pickSoftThreshold(
  BioMe_proteome_Neurology_wide[,-1],             # <= Input data
  #blockSize = 30,
  powerVector = powers,
  verbose = 5
  )

par(mfrow = c(1,2));
cex1 = 0.9;

plot(sft$fitIndices[, 1],
     -sign(sft$fitIndices[, 3]) * sft$fitIndices[, 2],
     xlab = "Soft Threshold (power)",
     ylab = "Scale Free Topology Model Fit, signed R^2",
     main = paste("Scale independence")
)
text(sft$fitIndices[, 1],
     -sign(sft$fitIndices[, 3]) * sft$fitIndices[, 2],
     labels = powers, cex = cex1, col = "red"
)
abline(h = 0.90, col = "red")
plot(sft$fitIndices[, 1],
     sft$fitIndices[, 5],
     xlab = "Soft Threshold (power)",
     ylab = "Mean Connectivity",
     type = "n",
     main = paste("Mean connectivity")
)
text(sft$fitIndices[, 1],
     sft$fitIndices[, 5],
     labels = powers,
     cex = cex1, col = "red")
```


```{r, include=FALSE}
picked_power = 3
temp_cor <- cor       
cor <- WGCNA::cor         # Force it to use WGCNA cor function (fix a namespace conflict issue)
netwk <- blockwiseModules(BioMe_proteome_Neurology_wide[,-1],                # <= input here

                          # == Adjacency Function ==
                          power = picked_power,                # <= power here
                          networkType = "signed",

                          # == Tree and Block Options ==
                          deepSplit = 2,
                          pamRespectsDendro = F,
                          # detectCutHeight = 0.75,
                          minModuleSize = 30,
                          maxBlockSize = 4000,

                          # == Module Adjustments ==
                          reassignThreshold = 0,
                          mergeCutHeight = 0.25,

                          # == TOM == Archive the run results in TOM file (saves time)
                          saveTOMs = T,
                          saveTOMFileBase = "ER",

                          # == Output Options
                          numericLabels = T,
                          verbose = 3)
```


```{r}
# Convert labels to colors for plotting
mergedColors = labels2colors(netwk$colors)
# Plot the dendrogram and the module colors underneath
plotDendroAndColors(
  netwk$dendrograms[[1]],
  mergedColors[netwk$blockGenes[[1]]],
  "Module colors",
  dendroLabels = FALSE,
  hang = 0.03,
  addGuide = TRUE,
  guideHang = 0.05 )

# netwk$colors[netwk$blockGenes[[1]]]

table(mergedColors)
```

```{r, include=FALSE}
module_df <- data.frame(
  gene_id = names(netwk$colors),
  colors = labels2colors(netwk$colors)
)

module_df[1:5,]
#>            gene_id    colors
#> 1 AC149818.2_FG001      blue
#> 2 AC149829.2_FG003      blue
#> 3 AC182617.3_FG001      blue
#> 4 AC186512.3_FG001 turquoise
#> 5 AC186512.3_FG007 turquoise

# write_delim(module_df,
#             file = "gene_modules.txt",
#             delim = "\t")
```



```{r}
expr_normalized=t(BioMe_proteome_Neurology_wide[,-1])
# pick out a few modules of interest here
modules_of_interest = c("blue", "grey", "turquoise")

# Pull out list of genes in that module
submod = module_df %>%
  subset(colors %in% modules_of_interest)

row.names(module_df) = module_df$gene_id

# Get normalized expression for those genes
expr_normalized[1:5,1:10]
#>                       B-3      B-4      B-5      L-3      L-4      L-5      S-3
#> AC149818.2_FG001 7.600901 7.077399 7.803434 7.220840 7.410408 8.028223 7.160846
#> AC149829.2_FG003 8.782014 8.179876 7.900062 8.299778 7.529891 8.631731 8.055118
#> AC182617.3_FG001 8.047244 7.120668 6.885533 7.501391 7.279413 7.809565 7.184253
#> AC186512.3_FG001 6.901539 7.389644 6.975945 6.859593 7.370816 6.633722 7.798843
#> AC186512.3_FG007 7.919688 7.754506 7.670946 7.417760 7.988427 7.904850 7.484542
#>                       S-4      S-5   B_L1.1
#> AC149818.2_FG001 7.401382 7.345322 6.524435
#> AC149829.2_FG003 8.744502 8.142909 8.240407
#> AC182617.3_FG001 8.140134 6.972400 7.777347
#> AC186512.3_FG001 6.949501 6.952659 6.059033
#> AC186512.3_FG007 8.375664 7.762799 6.335663
subexpr = expr_normalized[submod$gene_id,]

submod_df = data.frame(subexpr) %>%
  mutate(
    gene_id = row.names(.)
  ) %>%
  pivot_longer(-gene_id) %>%
  mutate(
    module = module_df[gene_id,]$colors
  )

submod_df %>% ggplot(., aes(x=name, y=value, group=gene_id)) +
  geom_line(aes(color = module),
            alpha = 0.2)+
         scale_color_manual(drop = FALSE,
                            values = c("blue", "grey", "turquoise"),
                            labels = c("blue", "grey", "turquoise")) +
  theme_classic() +
  theme(
    axis.text.x = element_text(angle = 90)
  ) +
  facet_grid(rows = vars(module)) +
  labs(x = "sample ID",
       y = "normalized expression")
```






