---
title: "BioMe PFAS & Inflammation proteomics"
author: "Meizhen Yao"
date: "`r Sys.Date()`"
output:
  html_document:
    theme: united
    highlight: tango
    df_print: paged
    fig_caption: yes
    fig_height: 7
    fig_width: 10
    number_sections: yes
    toc: yes
    toc_float:
      collapsed: yes
      smooth_scroll: yes
    self_contained: yes
    code_folding: hide
    toc_depth: 6
header-includes: \usepackage{multirow}
editor_options: 
  chunk_output_type: console
---

<style type="text/css">
body{
  /*font-family: Helvetica;*/
  font-size: 12pt;
}
</style>


```{r setup, include=FALSE}
options(digits = 4)
knitr::opts_chunk$set(echo = TRUE,tidy=TRUE,cache=F,warning = FALSE)
# suppress warning messages for final rendering
old.warn <- getOption("warn")
options(qwraps2_markup = "markdown")

```


```{r, include=FALSE}
# function
# volcano plot: show Gene label
olink_volcano_gene_plot<- function (p.val_tbl, x_lab = "Estimate", olinkid_list = NULL, 
    ...) 
{
    if (length(list(...)) > 0) {
        ellipsis_variables <- names(list(...))
        if (length(ellipsis_variables) == 1) {
            if (!(ellipsis_variables == "coloroption")) {
                stop(paste0("The ... option only takes the coloroption argument. ... currently contains the variable ", 
                  ellipsis_variables, "."))
            }
        }
        else {
            stop(paste0("The ... option only takes one argument. ... currently contains the variables ", 
                paste(ellipsis_variables, collapse = ", "), "."))
        }
    }
    if (is.null(olinkid_list)) {
        olinkid_list <- p.val_tbl %>% dplyr::filter(Threshold == 
            "Significant") %>% dplyr::pull(OlinkID)
    }
    volcano_plot <- p.val_tbl %>% ggplot2::ggplot(ggplot2::aes(x = estimate, 
        y = -log10(p.value), color = Threshold)) + ggplot2::geom_point() + 
        ggplot2::labs(x = x_lab, y = "-log10(p-value)") + ggrepel::geom_label_repel(size=10, data = subset(p.val_tbl, 
        OlinkID %in% olinkid_list), ggplot2::aes(label = Assay), 
        box.padding = 1, show.legend = FALSE) + ggplot2::geom_hline(yintercept = -log10(0.05), 
        linetype = "dotted") + OlinkAnalyze::set_plot_theme() + 
        OlinkAnalyze::olink_color_discrete(...)
    return(volcano_plot)
}

# volcano plot: show Protein label
olink_volcano_protein_plot<- function (p.val_tbl, x_lab = "Estimate", olinkid_list = NULL, 
    ...) 
{
    if (length(list(...)) > 0) {
        ellipsis_variables <- names(list(...))
        if (length(ellipsis_variables) == 1) {
            if (!(ellipsis_variables == "coloroption")) {
                stop(paste0("The ... option only takes the coloroption argument. ... currently contains the variable ", 
                  ellipsis_variables, "."))
            }
        }
        else {
            stop(paste0("The ... option only takes one argument. ... currently contains the variables ", 
                paste(ellipsis_variables, collapse = ", "), "."))
        }
    }
    if (is.null(olinkid_list)) {
        olinkid_list <- p.val_tbl %>% dplyr::filter(Threshold == 
            "Significant") %>% dplyr::pull(OlinkID)
    }
    volcano_plot <- p.val_tbl %>% ggplot2::ggplot(ggplot2::aes(x = estimate, 
        y = -log10(p.value), color = Threshold)) + ggplot2::geom_point() + 
        ggplot2::labs(x = x_lab, y = "-log10(p-value)") + ggrepel::geom_label_repel(size=10, data = subset(p.val_tbl, 
        OlinkID %in% olinkid_list), ggplot2::aes(label = Protein_name), 
        box.padding = 1, show.legend = FALSE) + ggplot2::geom_hline(yintercept = -log10(0.05), 
        linetype = "dotted") + OlinkAnalyze::set_plot_theme() + 
        OlinkAnalyze::olink_color_discrete(...)
    return(volcano_plot)
}


```



```{r, include=FALSE}
library(tidyverse)
library(ggpubr)
library(data.table)
library(readr)
library(readxl)
library(formattable)
library(ComplexHeatmap)
library(OlinkAnalyze)
library(gtsummary)
library(flextable)
library(ggplotify)
library(pheatmap)
library(plotly)
library(gapminder)
library(ggfortify)
library(reactable)


## import data
BioMe_proteome_PFAS_long <- fread("~/Projects/BioMe/proteome/input/analysis_sample/BioMe_proteome_PFAS_long.txt")



## dichotomous PFDA 

BioMe_proteome_PFAS_long$PFDA_Aug21_bi<- factor(BioMe_proteome_PFAS_long$PFDA_Aug21_bi,
                                                levels = c("Higher PFDA", "Lower PFDA"))


## restrict to inflammation panel
BioMe_proteome_PFAS_long_inflam<- BioMe_proteome_PFAS_long %>% 
                                  filter(Panel == "Inflammation")
# perform t-test
ttest_results <- olink_ttest(df = BioMe_proteome_PFAS_long_inflam,
                             variable = 'PFDA_Aug21_bi',
                             alternative = 'two.sided')

ttest_results$Threshold<- ifelse(ttest_results$p.value<0.05, "Significant", "Non-significant")

ttest_results<- ttest_results %>% 
                left_join(BioMe_proteome_PFAS_long_inflam[,c("OlinkID", "Protein_name")], by="OlinkID") %>% 
                distinct()

```


```{r, include=FALSE}
# select names of proteins to show
top_10_name <- ttest_results %>%
  slice_head(n = 3)  %>%
  pull(OlinkID)



jpeg("~/Projects/BioMe/proteome/output/PFAS vs. inflammation/PFAS_inflammation_protein_10_ttest.jpeg",
     units="in", width=16, height=12, res=500)

olink_volcano_protein_plot(p.val_tbl = ttest_results,
                   x_lab = 'Estimated Difference in Mean Normalized Protein Expression',
                   olinkid_list = top_10_name)+
  xlim(-0.7, 0.7)+
  labs(title="Inflammation proteomics vs. PFDA (Higher vs. Lower)")+
  theme_bw()+
  theme(
    title=element_text(size=24, color="black", face="bold"),
    legend.text=element_text(size=20, color="black", face="bold"),
    axis.text=element_text(size=14, color="black")
  )

dev.off()




```


```{r, include=FALSE}
# select names of proteins to show
top_10_name <- ttest_results %>%
  filter(Assay %in% c("FSTL3", "IL1RN")) %>%
  pull(OlinkID)



# volcano plot: show Protein label

jpeg("~/Projects/BioMe/proteome/output/PFAS vs. inflammation/PFAS_inflammation_gene_ttest.jpeg",
     units="in", width=16, height=12, res=500)
olink_volcano_gene_plot(p.val_tbl = ttest_results,
                   x_lab = 'Estimated Difference in Mean Normalized Protein Expression',
                   olinkid_list = top_10_name)+
  xlim(-0.7, 0.7)+
  labs(title="Inflammation proteomics vs. PFDA (Higher vs. Lower)")+
  theme_bw()+
  theme(
    title=element_text(size=20, color="black", face="bold"),
    legend.text=element_text(size=18, color="black", face="bold"),
    axis.text=element_text(size=14, color="black")
  )

dev.off()


# volcano plot: show Protein label

jpeg("~/Projects/BioMe/proteome/output/PFAS vs. inflammation/PFAS_inflammation_protein_ttest.jpeg",
     units="in", width=16, height=12, res=500)

olink_volcano_protein_plot(p.val_tbl = ttest_results,
                   x_lab = 'Estimated Difference in Mean Normalized Protein Expression',
                   olinkid_list = top_10_name)+
  xlim(-0.7, 0.7)+
  labs(title="Inflammation proteomics vs. PFDA (Higher vs. Lower)")+
  theme_bw()+
  theme(
    title=element_text(size=24, color="black", face="bold"),
    legend.text=element_text(size=20, color="black", face="bold"),
    axis.text=element_text(size=14, color="black")
  )

dev.off()




```





















